### ISSUE TITLE
Scharf s "ß" im Autorennamen der Arbeit

### ISSUE THREAD

**Issue by trin94** [StefanMacke/latex-vorlage-masterarbeit#2]
Hallo

vielen Dank für diese tolle Vorlage!

Mir ist aufgefallen, dass wenn der Autor ein "ß" im Namen hat, das Doppel-S auf dem Deckblatt vorkommt. Später im Text (beispielsweise im Kapitel EInleitung) klappt dann alles perfekt.
(Hatte die Daten in der Meta.tex angepasst.)

Viele Grüße
Elias

**Comment by StefanMacke** [comment]
Hallo Elias,

das liegt daran, dass Versalien (Großbuchstaben) verwendet werden. Und ein großes "ß" gibt es nicht.

Viele Grüße!
Stefan
